---
title: "Data Import"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

##Load in a dataset

```{r}
##read in a dataset - always use in a relative path as opposed to an absolute path

litters_data = read_csv(file = "./data/FAS_litters.csv") 

##litters_data = read_csv(file = "./data/FAS_litters.csv" skip = 10, col_names = FALSE) ##This will tell R to skip 10 lines of data and it will not assume column variable names. if you want those named, you will have to go in and rename them)  

##can run either litters_data to get a summary of data or run view(litters_data) to get a table view of all data

#janitor = package (could also do library(janitor) at top of page and then do not need to include janitor in the code below. Often he won't load the janitor package as a library, because janitor has other functions with the same names as other libraries (like tidyverse); therefore, to avoid confusing R, did not include (library(janitor)))

litters_data=janitor::clean_names(litters_data) 
litters_data
names(litters_data)#this code is rewriting litters_data so that we dont have duplicate datasets
```

##Load in pups_data
```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")

pups_data=janitor::clean_names(litters_data) 
pups_data
names(pups_data)

## to view dataset view(pups_data)
```

###provides you with summary stats, historic, information on some of the variables
skimr::skim(litters_data)  


###playing with column parsing
```
### double = R jargon for number

litters_data = read_csv(
  file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(), 
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
```


## Read in excel file...

```{r}
mlb11_data = 
  read_excel("data/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)

```

## Read in SAS...
```
library(haven)
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```
